### ISSUE TITLE
Nordic Thingy:91 (nRF9160) - unable to build softsim_static_profile sample using nRF v2.6.1 SDK - region `FLASH' overflowed

### ISSUE THREAD

**Issue by jameslshannon** [onomondo/nrf-softsim#49]
Hi,

When trying to build the latest softsim_static_profile sample using nRF 2.6.1 SDK (for board nrf9160_ns) it fails due to a flash overflow - is this a known issue with the provided minimal sample and how is it resolved?

```
c:/ncs/toolchains/cf2149caf2/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: address 0x1a120 of bin\tfm_s.axf section `.TFM_UNPRIV_CODE' is not within region `FLASH'
c:/ncs/toolchains/cf2149caf2/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: bin\tfm_s.axf section `.psa_interface_thread_fn_call' will not fit in region `FLASH'
c:/ncs/toolchains/cf2149caf2/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: address 0x1fc40 of bin\tfm_s.axf section `.gnu.sgstubs' is not within region `FLASH'
c:/ncs/toolchains/cf2149caf2/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: address 0x1a120 of bin\tfm_s.axf section `.TFM_UNPRIV_CODE' is not within region `FLASH'
c:/ncs/toolchains/cf2149caf2/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: address 0x1fc40 of bin\tfm_s.axf section `.gnu.sgstubs' is not within region `FLASH'
c:/ncs/toolchains/cf2149caf2/opt/zephyr-sdk/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.exe: region `FLASH' overflowed by 32100 bytes
Memory region         Used Size  Region Size  %age Used
           FLASH:       80740 B      48640 B    166.00%
             RAM:       47636 B        88 KB     52.86%
collect2.exe: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
[21/346] Completed 'mcuboot_subimage'
```

Thanks,

James

**Comment by MirkoCovizzi** [comment]
Hi James, this build failure is caused by an overflow of the `tfm` partition due to an increase of the TFM binary due to security requirements introduced by SoftSIM. The Thingy91, compared to a more basic nrf9160, supports MCUBOOT out of the box, which is configured, together with other components, in a static partition layout within NCS that can be found in `nrf/boards/arm/thingy91_nrf9160`. This static partition layout is loaded by default by the build system and it does not support SoftSIM due to a smaller size of the `tfm` partition. To resolve the issue, I made a PR to this repository with a solution. The PR can be found here: https://github.com/onomondo/nrf-softsim/pull/50

Please feel free to check out the PR and let me know if this resolves the issue for you.

**Comment by benjaminbruun** [comment]
Thanks for the contribution Mirko.
We have tested the new build configuration with success.

Be sure to open a new issue if new errors occur.

**Comment by jameslshannon** [comment]
Yes, I can also confirm that it now builds for Thingy:91 - thanks!
